#! /usr/bin/env php

<?php

use Revati\Packager\Template\InitCommand as InitTemplateCommand;
use Symfony\Component\Console\Application;

if( file_exists( __DIR__ . '/vendor/autoload.php' ) )
{
	require __DIR__ . '/vendor/autoload.php';
}
else
{
	require __DIR__ . '/../../autoload.php';
}

$app = new Application( "Package development wrapper", "0.0" );

$app->add( new InitTemplateCommand() );
//$app->add( new SaveTemplateCommand() );
//$app->add( new InitPackagerCommand() );

$app->run();