#! /usr/bin/env php

<?php

use Packager\Commands\AddPackageTypeCommand;
use Packager\Commands\SetupCommand;
use Packager\Commands\NewPackageCommand;
use Packager\Commands\ShowTypesListCommand;
use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$app = new Application( "Package development wrapper", "0.0" );

$app->add( new SetupCommand() );
$app->add( new NewPackageCommand() );
$app->add( new AddPackageTypeCommand() );
$app->add( new ShowTypesListCommand() );

$app->run();